//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anothermvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDetail
    {
        public string higesteducation { get; set; }
        public string status { get; set; }
        public Nullable<int> age { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public bool IsSelected { get; set; }
    }
}
